[startup.tfchaind]
name = "core.system"
protected = true

[startup.tfchaind.args]
name = "/bin/tfchaind"
# should use default values here?
args = ["--rpc-addr={TFCHAIND_RPC_ADDR}", "--api-addr={TFCHAIND_APIADDR}", "--persistent-directory", "/mnt/data " , "--network={TFCHAIND_NETWORK}", "--ethvalidation"]

